"""init models

Revision ID: 8f163e897934
Revises: 
Create Date: 2025-11-06 18:32:49.183402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f163e897934'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_allergen', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cook_time_min', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cate_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cate_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cook_instruction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step', sa.Text(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('need',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'ingredient_id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_review_rating_range'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cart')
    op.drop_table('record')
    op.drop_table('member')
    op.drop_table('product')
    op.drop_table('order_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_list',
    sa.Column('oid', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('mid', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ordertime', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('price', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('tno', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('product',
    sa.Column('pid', sa.VARCHAR(length=26), autoincrement=False, nullable=True),
    sa.Column('pname', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('price', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('pdesc', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('member',
    sa.Column('mid', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('account', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('identity', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('lname', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('fname', sa.VARCHAR(length=128), autoincrement=False, nullable=True)
    )
    op.create_table('record',
    sa.Column('tno', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('pid', sa.VARCHAR(length=26), autoincrement=False, nullable=True),
    sa.Column('amount', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('saleprice', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('total', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('cart',
    sa.Column('mid', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('carttime', sa.VARCHAR(length=26), autoincrement=False, nullable=True),
    sa.Column('tno', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.drop_table('review')
    op.drop_table('need')
    op.drop_table('cook_instruction')
    op.drop_table('recipe')
    op.drop_table('user')
    op.drop_table('ingredient')
    op.drop_table('category')
    # ### end Alembic commands ###
